# Generated by Django 5.1.6 on 2025-02-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicaltokenintegration_tokenintegration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenintegration',
            options={'permissions': [('renew_token', 'Pode renovar tokens')]},
        ),
        migrations.RemoveIndex(
            model_name='tokenintegration',
            name='core_tokeni_created_e1e348_idx',
        ),
        migrations.RemoveIndex(
            model_name='tokenintegration',
            name='core_tokeni_updated_9a519d_idx',
        ),
        migrations.RemoveIndex(
            model_name='tokenintegration',
            name='core_tokeni_deleted_b4eefd_idx',
        ),
    ]
