# Generated by Django 5.1.6 on 2025-02-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tokenintegration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenintegration',
            options={'permissions': [('renew_token', 'Can Renew Token')]},
        ),
    ]
