# Generated by Django 5.1.6 on 2025-02-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_apikey_historicalapikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, editable=False, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalapikey',
            name='key',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=128),
        ),
    ]
